channels:
    - defaults
    - pytorch
dependencies:
    - python=3.7
    - ipykernel
    - numpy
    - pandas
    - matplotlib
    - seaborn
    - psutil     # tensorflow-datasets
    - ipywidgets # tensorflow-datasets
    - pydot      # tf.keras.utils.plot_model
    - graphviz   # tf.keras.utils.plot_model
    - pytorch==1.4.0
    - pip
    - pip:
        - tensorflow==2.1.0
        - tensorflow-probability==0.9.0
        - tensorflow-datasets==2.0.0
        - gym[atari,box2d,classic_control]
