dependencies:
    - python=3.7
    - ipykernel
    - numpy
    - matplotlib
    - seaborn
    - psutil # tensorflow-datasets
    - ipywidgets # tensorflow-datasets
    - pydot # tf.keras.utils.plot_model
    - graphviz # tf.keras.utils.plot_model
    - pip
    - pip:
        - {{TENSORFLOW_PKG}}==2.0.0b1
        - tensorflow-probability==0.7.0
        - tensorflow-datasets==1.0.2
