dependencies:
    - python=3.7
    - ipykernel
    - numpy
    - pandas
    - matplotlib
    - seaborn
    - psutil     # tensorflow-datasets
    - ipywidgets # tensorflow-datasets
    - pydot      # tf.keras.utils.plot_model
    - graphviz   # tf.keras.utils.plot_model
    - pip
    - pip:
        - {{TENSORFLOW_PKG}}==2.0.0
        - tensorflow-probability==0.8.0
        - tensorflow-datasets==1.3.2
